name: wellness_tracker_app
description: A personal wellness tracking app using local SQLite database.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
