// lib/data/quotes.dart

const List<String> dailyQuotes = [
  "Success starts with self-discipline.",
  "Sweat. Smile. Repeat.",
  "A one hour workout is 4% of your day. No excuses.",
  "A healthy outside starts from the inside.",
  "Your body can stand almost anything. It’s your mind that you have to convince.",
  "Take care of your body. It's the only place you have to live.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Fitness is not about being better than someone else. It's about being better than you used to be.",
  "Don’t limit your challenges. Challenge your limits.",
  "Strive for progress, not perfection.",
  "Push yourself because no one else is going to do it for you.",
  "Discipline is choosing between what you want now and what you want most.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The body achieves what the mind believes.",
  "It never gets easier. You just get stronger.",
  "Take care of your body, it’s the only place you have to live.",
  "If it doesn’t challenge you, it doesn’t change you.",
  "Sweat is just fat crying.",
  "You don’t have to be extreme, just consistent.",
  "You are your only limit.",
  "Dream big. Work hard. Stay focused.",
  "Don’t watch the clock; do what it does. Keep going.",
  "A fit body, a calm mind, a house full of love. These things cannot be bought—they must be earned.",
  "Every workout counts, even if it's just 10 minutes.",
  "Perseverance is not a long race; it's many short races one after another.",
  "The difference between try and triumph is a little umph.",
  "Work hard in silence, let success be your noise.",
  "Fall in love with taking care of yourself.",
  "Don’t count the days, make the days count.",
  "Excuses don’t burn calories.",
  "Fitness is like a relationship. You can’t cheat and expect it to work.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Believe in yourself and all that you are.",
  "Strong is the new sexy.",
  "Change your body by changing your thoughts.",
  "The groundwork for all happiness is good health.",
  "Your health is an investment, not an expense.",
  "A champion is someone who gets up when they can’t.",
  "Success is the sum of small efforts repeated day in and day out.",
  "You are what you do, not what you say you’ll do.",
  "No pain, no gain. Shut up and train.",
  "Be stronger than your excuses.",
  "You don’t find willpower, you create it.",
  "Make yourself a priority.",
  "The body achieves what the mind believes.",
  "Small steps every day.",
  "Train insane or remain the same.",
  "You are what you repeatedly do.",
  "Fitness is not a destination, it’s a way of life.",
  "No matter how slow you go, you’re still lapping everyone on the couch.",
  "Believe you can and you’re halfway there.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Your only limit is your mind.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
  "The only bad workout is the one that didn’t happen.",
  "Today I will do what others won’t, so tomorrow I can do what others can’t.",
  "Pain is temporary. Quitting lasts forever.",
  "Train like a beast, look like a beauty.",
  "Wellness is the natural state of my body.",
  "Take the time to make your soul happy.",
  "Create healthy habits, not restrictions.",
  "Move your body, still your mind.",
  "The future depends on what you do today.",
  "The best project you’ll ever work on is you.",
  "You don’t get what you wish for. You get what you work for.",
  "You didn’t come this far to only come this far.",
  "Stop doubting yourself, work hard, and make it happen.",
  "Energy and persistence conquer all things.",
  "Strong mind. Strong body.",
  "Healthy isn’t a goal, it’s a way of living.",
  "Let your dreams be bigger than your fears.",
  "Make your body the sexiest outfit you own.",
  "Don’t wish for a good body, work for it.",
  "Start where you are. Use what you have. Do what you can.",
  "Fall seven times, stand up eight.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Sweat more, bitch less.",
  "Health is not just about what you’re eating. It’s also about what you’re thinking and saying.",
  "Your body deserves the best.",
  "You have to expect things of yourself before you can do them.",
  "Results happen over time, not overnight.",
  "You are capable of amazing things.",
  "The mind is everything. What you think you become.",
  "Pain is weakness leaving the body.",
  "Health is the greatest gift.",
  "Take the risk or lose the chance.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Little by little, a little becomes a lot.",
  "Your future self will thank you for what you do today.",
];